language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - git clone https://github.com/futures/fcrepo4.git
  - cd fcrepo4
  - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=1024m"
  - mvn clean install -DskipTests=true
  - cd ..
  - PEARTREEVER=1.1.1
  - PEARTREEJAR=pairtree-$PEARTREEVER.jar
  - wget -O $PEARTREEJAR http://downloads.sourceforge.net/project/loc-xferutils/loc-pairtree-java-library/$PEARTREEJAR?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Floc-xferutils%2Ffiles%2Floc-pairtree-java-library%2F&ts=1384173580&use_mirror=heanet
  - mvn install:install-file -Dfile=$PEARTREEJAR -DartifactId=pairtree -Dversion=$PEARTREEVER -DgroupId=gov.loc -Dpackaging=jar
  - cd ..
