language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - git clone https://github.com/futures/fcrepo4.git
  - cd fcrepo4
  - git checkout fcrepo-4.0.0-scape
  - mvn -q clean install -DskipTests=true
  - cd ..
